[package]
name = "vectorless-graph"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
vectorless-config = { path = "../vectorless-config" }
vectorless-document = { path = "../vectorless-document" }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
