[package]
name = "vectorless-scoring"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
bm25 = { workspace = true }
regex = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
