// Copyright (c) 2026 vectorless developers
// SPDX-License-Identifier: Apache-2.0

//! Tree structure using indextree (Arena-based).
//!
//! This module provides a more idiomatic Rust tree implementation using the `indextree` crate.
//! Instead of the Python-style `Rc<RefCell<PageNode>` pattern.

//! The approach uses arena allocation where all nodes are stored in a contiguous
//! vector and referenced by indices (NodeId), which provides:
//! better memory locality, cache-friendly access, and safer concurrency.

//!
//! # Example
//!
//! ```rust
//! use vectorless::tree::{DocumentTree, TreeNode, NodeId};
//!
//! // Create a new tree
//! let mut tree = DocumentTree::new("Root", "Root content");
//!
//! // Add children
//! let child1 = tree.add_child("Child 1", "Content 1");
//! let child2 = tree.add_child("Child 2", "Content 2");
//!
//! // Navigate the tree
//! for node_id in tree.root().children(&tree) {
//!     let node = tree.get(node_id);
//!     println!("Title: {}", node.title);
//! }
//! ```

use indextree::{Arena, NodeId as IndexTreeNodeId};
use serde::{Deserialize, Serialize};
use std::fmt;

/// Unique identifier for a node in the document tree.
///
/// This is a newtype wrapper around indextree's NodeId to provide
/// better type safety and domain-specific semantics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NodeId(IndexTreeNodeId);

// Implement traits for interoperability
impl fmt::Display for NodeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "NodeId({:?})", self.0)
    }
}

impl Serialize for NodeId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.0.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for NodeId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let id = IndexTreeNodeId::deserialize(deserializer)?;
        Ok(NodeId(id))
    }
}

/// A node in the document tree.
///
/// Each branch represents a section and each leaf contains the actual text.
/// When a question is asked, an LLM navigates this tree level by level
/// to find the right answer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TreeNode {
    /// Title of this section.
    pub title: String,

    /// Raw text content (populated at leaves).
    #[serde(default)]
    pub content: String,

    /// Generated by LLM summary.
    #[serde(default)]
    pub summary: String,

    /// Depth in tree (0 = root, 1 = section, 2 = subsection, etc.).
    #[serde(default)]
    pub depth: usize,

    /// Starting page number (1-based, if applicable).
    pub start_page: Option<usize>,

    /// Ending page number (1-based, if applicable).
    pub end_page: Option<usize>,

    /// Unique node identifier (e.g., "0001", "0002").
    pub node_id: Option<String>,

    /// Physical index marker for line tracking.
    pub physical_index: Option<String>,

    /// Token count estimate.
    pub token_count: Option<usize>,
}

impl Default for TreeNode {
    fn default() -> Self {
        Self {
            title: String::new(),
            content: String::new(),
            summary: String::new(),
            depth: 0,
            start_page: None,
            end_page: None,
            node_id: None,
            physical_index: None,
            token_count: None,
        }
    }
}
